# Stage 1: Build the React app
FROM node:18-slim as build

WORKDIR /usr/src/app

COPY dashboard/package*.json ./
RUN npm install
COPY dashboard/ ./

RUN npm run build

# Stage 2: Serve the app with a static server
FROM node:18-slim

WORKDIR /usr/src/app

# Install `serve` to run the static files
RUN npm install -g serve

# Copy the built assets from the build stage
COPY --from=build /usr/src/app/build .

# Expose port 3000
EXPOSE 3000

# Run the server
CMD ["serve", "-s", ".", "-l", "3000"]
