version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5003:5003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Don't mount over the container's node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
