# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application's code
COPY . .

# Make port 5003 available to the world outside this container
EXPOSE 5003

# Define the command to run the app
CMD [ "node", "src/server.js" ]
